name: toy-ml
github: mitchellwrosen/toy-ml
license: BSD3

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base
    - distributive
    - foldl
    - hmatrix
    - linear
    - vector
